### ISSUE TITLE
Things to consider 

### ISSUE THREAD

**Issue by Kflash** [babel/babel-library-boilerplate#155] opened 2015-05-11 07:37 UTC
As it is with this build system, parts of it need refactoring to match with all node.js versions.

Example **path@newest** where path is a node module too. And use of **uglifyjs** where it's throws an warning. **uglify** should have been used.

There are other examples too. Many...

Except this performance need to be considered, and also some new features.
**gulp-header** is useful to add info to the top of the source file.  You see this everywhere.

Next is the coverage. Code climate force you to pay in the end. Adding an extra line in Travis.Yml is all it takes to get this working with coveralls.io. So need to consider to add this in, or at least mention it in the readme.

Another thing to mention in the readme is the *hidden* option people have when they can choose between UMD and AMD.  

**bundle.toUmd**

 in the gulp.js file, gives as stated a UMD version, but you can do:

**bundle.toAmd**

and get a AMD version. People should be informed about this configuration tweak.

Browserify is slow. But there is no other options then example es6-modules. Not sure if that is an option here.

For PhantomJS I don't have any fasit on that question, but one solution could be too refactor and use Karma in the bottom, and still use mocha for the test units. This will also make it easier with integration with SauceLabs repos are using. The con in this case is how to use ES6 in the test units, something I try to find a solution for in my own workflow at the moment.

Last would be to consider a template. That replace inline code example version with correct version from package.json.

And as a feature add version bumping.  

Version bumping is easy:

```javascript
gulp.task("bump", function() {
    return gulp.src(["./*.json"])
        .pipe(bump({
            version: argv.tag
        }))
        .pipe(gulp.dest("./"));
});
```

**Comment by Kflash** [comment] 2015-05-11 15:10
@jmeas I'm looking more deeply into all kind of conflicts with nodeJS and the things I mentioned as a consideration. And I found even more different issues.

I will come back to you as soon as I got things figured out. Meanwhile I can note that I put up my own boilerplate just now on my own repo where as an experiment to figure out things in this repo for you.

You can follow my progress there. I'm using karma, jasmine and phantomJS, but also babel and your ideas used in this repo.

**Comment by jmeas** [comment] 2015-05-11 15:18
@kflash, can you please limit issues to a single specific topic? This is really tough to follow...

In addition, because it covers so many things, it's tough to know when I'll be able to close this as done.

I really appreciate you wanting to help out with the project, but I like to keep things atomic and separate, so that it's easier to make progress!

Thanks!

**Comment by jmeas** [comment] 2015-05-11 15:18
For now, I'm going to close this as invalid. Please make separate issues that clearly state what the problem is. Thanks!

**Closed by jmeas** 2015-05-11 15:18 UTC

**Comment by Kflash** [comment] 2015-05-11 15:23
@jmeas Sure. I could done separate issues on this one, but I think my time is up. So not sure if I want to continue on contribution on this repo when you mark the thread as *invalid* when there are obvious bogus going on. But I give it a chance and will open a short issue.
