### ISSUE TITLE
specrunner.html not working

### ISSUE THREAD

**Issue by rickardjanson** [babel/babel-library-boilerplate#175] opened 2015-06-10 23:32 UTC
specrunner.html in test folder not working.

**Comment by jmeas** [comment] 2015-06-11 04:26
Works for me. What error are you getting?

Just to check, did you:

1. Run `npm install`
2. Compile the source and set up watch with `gulp test-browser`
3. Open the spec runner in your browser

**Comment by rickardjanson** [comment] 2015-06-11 04:55
Hi, @jmeas. Thanks for quick reply. Yes, I did all this things, and ended up with this message:

"before each" hook 
global.sinon is undefined
[3]</</module.exports/<@http://localhost/babel/tmp/__spec-build.js:44:9

and

"after each" hook 
this.sandbox is undefined
[3]</</module.exports/<@http://localhost/babel/tmp/__spec-build.js:54:9

Probably nothinghting to worry about :+1:

**Comment by jmeas** [comment] 2015-06-11 05:00
Interesting, @rickardjanson . I'll take another look tomorrow to see if I can reproduce it!

**Comment by rickardjanson** [comment] 2015-06-11 05:21
The connection to ws://localhost:35729/livereload was interrupted while the page was loading.
livereload.js (line 74)
Firefox can't establish a connection to the server at ws://localhost:35729/livereload.

**Comment by rickardjanson** [comment] 2015-06-11 08:14
The story goes like this....  3 fresh install on window computer - same shit. I went to the store and baught a new laptop and re-installed. This was with windows. It happened again.
Then I got frustrated, so I went back to the store and bought a mac. And re-installed. And whole!
Problem seems to be with fsevents(mac). Problems happened on windows.

Very expensive experience this one, but at least. This is my conclusion.

**Comment by jmeas** [comment] 2015-06-14 21:38
I don't have a PC to test on, so there's not much I can do : [

If you diagnose what the problem is, do let me know. Maybe once I get around to updating the dev dependencies it will automatically fix itself.

**Comment by rickardjanson** [comment] 2015-06-15 00:51
Hi. Updating the dev dependencies will cause issues I guess. The path for sinon seems to have changed in a newer version. To the `/lib` folder now. And I have no idea how I solved this issue on my own, but I ended up with upgrading the packages and discovered this. And after changing the path, it works now.

**Comment by rickardjanson** [comment] 2015-06-15 01:00
@jmeas I forgot to mention... I also renamed the `gulpfile.js` to `gulpfile-babel.js`  and re-wrote it into ES6. Something new you can do with newest babel version. I have no idea if this too helped me solve the issue, but I just mention it here just in case.

**Comment by megawac** [comment] 2015-06-15 01:26
Awesome! Could you do a pull request with those changes?

**Comment by rickardjanson** [comment] 2015-06-15 07:42
@megawac I have no time this week, but it's very easy task if you think about the `gulpfile`.
Take a look at this Twitter post: https://twitter.com/wesbos/status/608987962370424832

For the `sinon` issue look at this line:  https://github.com/babel/babel-library-boilerplate/blob/master/test/runner.html#L14

What I did was changing `pkg` to `lib` after upgrading to a newer version.

**Comment by jmeas** [comment] 2015-07-30 05:29
Gonna close this as this seems to be related to updating sinon.

**Closed by jmeas** 2015-07-30 05:29 UTC
Labels: bug, windows

**Comment by jmeas** [comment] 2015-07-30 06:46
Hm, I took a look, and the `pkg` directory is what the sinon library exports. The file in `lib` should not work in the context of a browser...

For this reason, I think I'm going to keep it referencing `pkg` in the runner, unless I'm missin' something obvious here :question:
