### ISSUE TITLE
throws warning with 'path

### ISSUE THREAD

**Issue by Kflash** [babel/babel-library-boilerplate#157] opened 2015-05-11 15:44 UTC
@jmeas   nodeJS throws a warning on **path**. Where path also is an module in nodejS.

**Comment by jmeas** [comment] 2015-05-11 15:50
Can you provide more details, @kflash? When does NodeJS throws an error? And what version of node are you using?

**Comment by Kflash** [comment] 2015-05-11 15:53
@jmeas nodeJS v. 12.x. It comes up when I build the repo, and also in TravisCI

**Comment by jmeas** [comment] 2015-05-11 16:01
@kflash, maybe I'm being dum here, but I can't reproduce it. And I looked at the Travis logs and didn't see the warning there, either. Am I missing something obvious?

By 'build the repo,' what do you mean? Do you mean installing the dependencies, or building the library?

Building the library:

![](https://cldup.com/U4qdZwkX4M.png)

I'd post the ss of installing the deps, but the text doesn't all fit on one page. I don't see a warning, though!

**Comment by Kflash** [comment] 2015-05-11 16:04
@jmeas I see you didn't get the warning. Strange. I got it the whole day.
Anyway. See documentation for nodeJS 12.2 here.  https://nodejs.org/api/path.html

Path is clearly a part of nodeJS@newest.

**Comment by Kflash** [comment] 2015-05-11 16:07
@jmeas This is not a new issue it seems. See stackOverflow: http://stackoverflow.com/questions/24897130/path-is-also-the-name-of-a-node-core-module

**Comment by jmeas** [comment] 2015-05-11 16:14
I know about `path`, and I've seen this issue before in other projects. I've just never seen it in this project before.

Is it cool to close this issue, then?

**Comment by Kflash** [comment] 2015-05-11 16:16
I think you can close it. People who sees it should know how to fix it. I'm off for a few minutes, trying to fix your ESlint.

**Closed** 2015-05-11 16:21 UTC
